name: Build Electron

on:
  push:
    branches: [ main,electron_client_side ]
  pull_request:
    branches: [ main,electron_client_side ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./electron
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
