name: Build Electron

on:
  workflow_dispatch:
  push:
    branches: [ mvp ]
    paths: ['electron/**']
  pull_request:
    branches: [ mvp ]
    paths: ['electron/**']

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./electron
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: D:\a\2023-project-immich\2023-project-immich\electron\dist
