name: Build Server Installer

on:
  push:
    branches: [ main,electron_client_side ]
  pull_request:
    branches: [ main,electron_client_side ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $env:TOKEN 
      - run: echo $env:TOKEN -eq 1 
        env: 
          TOKEN: "${{ secrets.TEST_SECRET }}"
